### ISSUE TITLE
[Quest][Npc] Smarts-is-smarts, Triumph Captain, Southern Barrens

### ISSUE THREAD

**Issue by Freemind0** [SallyWhitemane/Maelstrom#307]
**Description:**
The quest text mentions "Triumph Officer."
Afaik i cannot see such npc on the quest location.
However northen part of it i see a "Triumph Captain" which both shows as the target on the minimap + shows that hes the target.
And he gave me the item.

Theres also only 1 of this npc as far as i can see.
There should be multiple ones patrolling. He just stands still.

![image](https://user-images.githubusercontent.com/56369938/175364338-e5556426-252f-48f4-a346-370aa2abbec6.png)
![image](https://user-images.githubusercontent.com/56369938/175364532-c66ed599-b4d9-4539-a6df-f1191565ab61.png)

**How to reproduce:**

Pick up quest & move to the location of the npc & check quest text.
**How it should work:**
Npc should patrol & should be multiple ones.
Quest log should be "Triumph captain."

I got a video from 2016 to prove it. But it's not a Cataclysm aged video (although the player is 85, so hard to tell).
But it shows Triumph Captain, not officer.

https://www.youtube.com/results?search_query=Wow+cataclysm+Smarts+is+smarts

**Comment by MrTide** [comment]
I assume patrolling also got fixed i will close https://github.com/SallyWhitemane/Maelstrom/issues/497 as duplicate with your permission @UltraNix 
Just FYI freemind0 any military member from rank Third lieutenant all the way up to Colonel are considered "officers" thats why quest mentions it as officer since captains are also considered officer.
